version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - .:/app
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - FIREBASE_CREDENTIALS=/app/storage/app/firebase/firebase-credentials.json
      - FIREBASE_PROJECT_ID=${FIREBASE_WEB_PROJECT_ID}
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=127.0.0.1
      - REDIS_PORT=6379
      - REDIS_PASSWORD=null
      - MEMCACHED_HOST=127.0.0.1
      - MEMCACHED_PORT=11211
    restart: unless-stopped
    tty: true
    network_mode: host

volumes:
  caddy_data:
  caddy_config:
