version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: antarkanma-nginx-lb
    volumes:
      - ./nginx-lb.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - antarkanma

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: antarkanma-cloudflared-lb
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token eyJhIjoiNjE1NzhkZDhiMzMxNzYyMzNlNGM3ZjI5MDYwMmJmMzUiLCJ0IjoiZmM3ZjU1ZjUtY2MwMi00Y2JhLTk5MTQtZmJmNmY2ZDI2ZjhkIiwicyI6Ik9UTTNNV1k0T0RRdE1XWTRNeTAwTkRFMkxXSmhaalV0TkRKbE9EZzVaVEExWlRFMiJ9
    depends_on:
      - nginx
    networks:
      - antarkanma

networks:
  antarkanma:
    driver: bridge
