version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: antarkanma-app
    restart: unless-stopped
    environment:
      - APP_NAME=${APP_NAME}
      - APP_ENV=${APP_ENV}
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=${APP_DEBUG}
      - APP_URL=${APP_URL}
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FIREBASE_PROJECT=app
      - FIREBASE_PROJECT_ID=antarkanma-98fde
      - FIREBASE_CREDENTIALS=/app/storage/app/firebase/firebase-credentials.json
      - FIREBASE_DATABASE_URL=${FIREBASE_DATABASE_URL}
      - FIREBASE_STORAGE_DEFAULT_BUCKET=${FIREBASE_STORAGE_DEFAULT_BUCKET}
      - FIREBASE_SERVER_KEY=${FIREBASE_SERVER_KEY}
      - FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}
      - FIREBASE_API_KEY=${FIREBASE_API_KEY}
    volumes:
      - .:/app:delegated
      - ./node_modules:/app/node_modules
      - /app/vendor
      - ./.env:/app/.env:ro
      - ./storage/app/firebase:/app/storage/app/firebase:ro
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - antarkanma

  db:
    image: mysql:8.0
    container_name: antarkanma-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - antarkanma

  redis:
    image: redis:alpine
    container_name: antarkanma-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - antarkanma

networks:
  antarkanma:
    driver: bridge

volumes:
  dbdata:
  redisdata:
