# Network and Security
bind 0.0.0.0
protected-mode yes
port 6379
timeout 300

# Authentication
requirepass AntarkanmaRedis123

# Persistence
appendonly yes
appendfilename "appendonly.aof"
appendfsync everysec

# Memory Management
maxmemory 256mb
maxmemory-policy allkeys-lru

# Logging
loglevel notice
logfile "/data/redis.log"
