# Network
bind 0.0.0.0
protected-mode yes
port 6379

# Authentication
requirepass AntarkanmaRedis123
masterauth AntarkanmaRedis123

# Replication
replicaof 103.181.143.176 6379
replica-serve-stale-data yes
replica-read-only no

# Persistence
appendonly yes
appendfilename "appendonly.aof"
appendfsync everysec

# Memory Management
maxmemory 256mb
maxmemory-policy allkeys-lru

# Logging
loglevel notice
logfile "/data/redis.log"
